### ISSUE TITLE
No master found for 'mymaster'

### ISSUE THREAD

**Issue by qghc** [SpiderClub/weibospider#93]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
你好，我按照快速开始的教程一步一步进行到第10步的时候提示（redis.sentinel.MasterNotFoundError: No master found for 'mymaster'），请问这是怎么回事？
2.你期望的结果是什么？
期望不报错，应该可以进行爬去任务。
3.实际上你得到的结果是什么？
报错（redis.sentinel.MasterNotFoundError: No master found for 'mymaster'）
4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？
WeiboSpider:1.7.2，操作系统：Linux-4.13.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
报错如下：
![ABC](https://upload-images.jianshu.io/upload_images/3473742-1a60775a295cd596.png)

**Comment by thekingofcity** [comment]
请检查下redis是否启动成功和spider.yaml的redis配置

**Comment by ResolveWang** [comment]
`spider.yaml`中你需要修改一下配置，麻烦看看配置的注释啊，配置文件的注释应该是有说明的
```
redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    cookies: 1                   # store and fetch cookies
    # store fetched urls and results,so you can decide whether retry to crawl the urls or not
    urls: 2
    broker: 5                    # broker for celery
    backend: 6                   # backed for celery
    id_name: 8                   # user id and names，for repost info analysis. Could be safely deleted after repost tasks
    expire_time: 48
    sentinel: ''   #  这里改为空
    master: ''             # 这里改为空
    socket_timeout: 5            
```
